const createChineseLabels = () => ({
  title: 'AI 编辑器',
  settings: 'AI 设置',
  model: '模型',
  modelHint: '切换后从下一次请求生效；当前请求使用已选模型。',
  reasoningEffort: '会话推理 effort',
  reasoningEffortModelDefault: '模型默认',
  reasoningEffortProviderDefault: 'Provider default',
  advancedCompatibility: '高级兼容选项（JSON 预设）',
  requestBodyPreset: '请求参数预设',
  requestBodyPresetHint: '仅影响下一次请求；预设内容来自模型或网关文档。',
  requestBodyPresetModelDefault: (value: string) => `模型默认（${value || '无额外 JSON'}）`,
  requestBodyPresetOmit: '本会话无额外 JSON',
  noModels: '请先在 AI 设置中添加模型',
  close: '关闭',
  answer: '回答',
  edit: '修改文档',
  answerHelp: '回答模式只提供建议，不会修改当前文档。',
  editHelp: '精确修改只应用模型指出的局部内容，可用 AI 撤销恢复。',
  rewrite: '全文重写',
  rewriteHelp: '全文重写会替换整篇 Markdown，请确认后再使用。',
  empty: '在这里开始与当前文档对话。',
  you: '你',
  ai: 'AI',
  failureOutputTitle: '查看模型原始输出（调试）',
  copyFailureOutput: '复制原始输出',
  copied: '已复制',
  failureOutputTruncated: '输出过长，已截断显示。',
  modelReasoning: '模型思考（仅供参考）',
  reasoningSummary: '推理摘要',
  placeholder: '输入问题或编辑指令…',
  attachHint: '粘贴或拖入图片或 PDF，也可点击选择',
  attachmentPrivacy: '附件会发送到当前配置的 AI 服务。',
  removeAttachment: '移除附件',
  attachmentUnsupported: '仅支持 PNG、JPEG、WebP、GIF 图片或 PDF。',
  attachmentTooLarge: '单张图片不能超过 10 MB。',
  attachmentPdfTooLarge: '单个 PDF 不能超过 20 MB。',
  attachmentTooMany: '一次最多添加 10 个附件。',
  attachmentTotalTooLarge: '一次附件总大小不能超过 30 MB。',
  attachmentReadFailed: '无法读取附件。',
  pdfPages: (count: number) => (count ? `共 ${count} 页` : '正在读取页数…'),
  pdfPagePlaceholder: '例如 1,3,5-8',
  pdfPageLabel: 'PDF 页面选择',
  pdfPagesRequired: '超过 10 页的 PDF 必须选择页面。',
  pdfInvalidPages: '页码格式无效，请使用如 1,3,5-8 的格式。',
  pdfBudget: (remaining: number) => `本次请求还可发送 ${remaining} 张图片（PDF 页面共用上限）。`,
  preparingPdf: '正在准备 PDF 页面…',
  sendHint: '点击发送按钮提交',
  working: 'AI 正在处理…',
  stop: '停止',
  thinking: '处理中…',
  send: '发送',
  clear: '清空对话',
  undo: '撤销 AI 修改',
  unconfigured: '未配置连接',
  editApplied: (count: number, added: number, removed: number) =>
    `已应用 ${count} 处修改（新增 ${added} 行，删除 ${removed} 行）`,
  editPlan: '编辑计划',
  planSteps: (count: number) => `共 ${count} 个步骤`,
  stepDeleted: '删除',
  stepAdded: '新增',
  emptyDiff: '（空）',
  noChanges: '文档无需修改',
  rewriteApplied: '已重写全文',
  recoveryWarning: '模型未能生成可靠的局部编辑，以下是整篇替代结果，请确认差异后应用。',
  recoveryApply: '应用替代结果',
  recoveryDiscard: '丢弃'
})

const createEnglishLabels = () => ({
  title: 'AI Editor',
  settings: 'AI settings',
  model: 'Model',
  modelHint: 'Changes apply to the next request; the current request keeps its model.',
  reasoningEffort: 'Session reasoning effort',
  reasoningEffortModelDefault: 'Model default',
  reasoningEffortProviderDefault: 'Provider default',
  advancedCompatibility: 'Advanced compatibility options (JSON presets)',
  requestBodyPreset: 'Request parameter preset',
  requestBodyPresetHint: 'Applies only to the next request; use JSON from the model or gateway documentation.',
  requestBodyPresetModelDefault: (value: string) => `Model default (${value || 'no extra JSON'})`,
  requestBodyPresetOmit: 'No extra JSON for this session',
  noModels: 'Add a model in AI settings first',
  close: 'Close',
  answer: 'Answer',
  edit: 'Edit document',
  answerHelp: 'Answer mode provides suggestions only and never changes the document.',
  editHelp: 'Precise edit applies only the requested local changes and supports AI undo.',
  rewrite: 'Rewrite document',
  rewriteHelp: 'Rewrite replaces the complete Markdown document. Use it intentionally.',
  empty: 'Start a conversation about the current document.',
  you: 'You',
  ai: 'AI',
  failureOutputTitle: 'View raw model output (debug)',
  copyFailureOutput: 'Copy raw output',
  copied: 'Copied',
  failureOutputTruncated: 'The output was too long and has been truncated.',
  modelReasoning: 'Model reasoning (informational)',
  reasoningSummary: 'Reasoning summary',
  placeholder: 'Ask a question or describe an edit…',
  attachHint: 'Paste, drop, or choose images or PDFs',
  attachmentPrivacy: 'Attachments are sent to the configured AI service.',
  removeAttachment: 'Remove attachment',
  attachmentUnsupported: 'Only PNG, JPEG, WebP, GIF images, or PDF files are supported.',
  attachmentTooLarge: 'Each image must be smaller than 10 MB.',
  attachmentPdfTooLarge: 'Each PDF must be smaller than 20 MB.',
  attachmentTooMany: 'You can attach up to 10 files at a time.',
  attachmentTotalTooLarge: 'Attachments in one request must total less than 30 MB.',
  attachmentReadFailed: 'The attachment could not be read.',
  pdfPages: (count: number) => (count ? `${count} pages` : 'Reading page count…'),
  pdfPagePlaceholder: 'For example 1,3,5-8',
  pdfPageLabel: 'PDF page selection',
  pdfPagesRequired: 'Select pages for PDFs with more than 10 pages.',
  pdfInvalidPages: 'Invalid page selection. Use a format such as 1,3,5-8.',
  pdfBudget: (remaining: number) =>
    `${remaining} image slots remain in this request (PDF pages share the limit).`,
  preparingPdf: 'Preparing PDF pages…',
  sendHint: 'Click Send to submit',
  working: 'AI is working…',
  stop: 'Stop',
  thinking: 'Working…',
  send: 'Send',
  clear: 'Clear chat',
  undo: 'Undo AI edit',
  unconfigured: 'Connection not configured',
  editApplied: (count: number, added: number, removed: number) =>
    `Applied ${count} edit${count === 1 ? '' : 's'} (+${added}/-${removed} lines)`,
  editPlan: 'Edit plan',
  planSteps: (count: number) => `${count} step${count === 1 ? '' : 's'}`,
  stepDeleted: 'Deleted',
  stepAdded: 'Added',
  emptyDiff: '(empty)',
  noChanges: 'No document changes were needed.',
  rewriteApplied: 'The document was rewritten.',
  recoveryWarning:
    'The model could not produce a reliable local edit. Review the complete-document fallback before applying it.',
  recoveryApply: 'Apply fallback',
  recoveryDiscard: 'Discard'
})

export type AiPanelLabels = ReturnType<typeof createEnglishLabels>

export const createAiPanelLabels = (chinese: boolean): AiPanelLabels =>
  chinese ? createChineseLabels() : createEnglishLabels()
